### ISSUE TITLE
Duplicate khi sử dụng tiếng việt

### ISSUE THREAD

**Issue by tvd12** [youngmonkeys/freechat#16]
### Môi trường:
- Hệ điều hàng: Mac OSX
- Trình duyệt chrome
- Input: tiếng việt simple telex
### Flow:
- Đăng nhập vào site: https://freechat.tvd12.com/login
- Đăng nhập bằng tài khoản bất kì, hệ thống sẽ tự tạo tài khoản
- Chọn vào Bot
- Sử dụng tiếng việt gõ â và nhấn enter
### Lỗi:
Input â và enter sẽ thấy 2 message giống hệt nhau như thế này:
![Screenshot 2021-05-13 at 13 08 00](https://user-images.githubusercontent.com/6251901/118085239-47038980-b3ec-11eb-9f6d-2e56ecdab09a.png)
File code: https://github.com/youngmonkeys/freechat/blob/master/reactjs/src/views/MessageView/MessageView.jsx#L473
### Nhờ các bạn
- Fork 1 bản về github của mình
- cd đến thư mục `freechat/reactjs`
- chạy `npm start` để chạy code
- Sau khi fix bug rồi hãy tạo 1 PR giúp mình nhé
Cám ơn mọi người!

**Comment by gialynguyen** [comment]
bạn thử dùng: onKeyPress thay cho onKeyDown nhan

**Comment by tvd12** [comment]
cám ơn @gialynguyen nhé, ok rồi
