### ISSUE TITLE
Displaying contacts/ messages data in flutter

### ISSUE THREAD

**Issue by DariusPrimarius** [youngmonkeys/freechat#28]
Looking for right way to display data from server.

At the moment i save data into array and use it with ListView.builder, unfortunatelly it's not refreshing when new contact appears. It is not possible to use set state inside datahandler.

My handler looks like that :

```dart
class _ContactsResponseHandler extends EzyAbstractDataHandler {
  @override
  handle(List data) {
    array = array + data[1][1];
    print(array);
    print(array.length);
    print('-----------------');
  }
}
```

And I'm displaying it with :

```dart
Container(
              height: 300,
              width: double.infinity,
              child: ListView.builder(
                itemCount: array.length,
                itemBuilder: (context, index) {
                  return ListTile(
                    title: Text(array[index]['users'].toString()),
                  );
                },
              ),
            )
```

Also swaping views/widgets back and forward generate some errors.

**Comment by tvd12** [comment]
@DariusPrimarius so do you mean, you can see the print log but the ListView did not refresh?

**Comment by DariusPrimarius** [comment]
Even better I can display data on the screen but I don't know how to rebuild widget when data changes. For example when I get  data list of contacts from server it's in form of list of dict's (i know that i should make a class Message but it's later). Example answer from server in log is : 

> [{channelId: 1, users: [example2]}, {channelId: 2, users: [example3]}, {channelId: 3, users: [example5]}, {channelId: 5, users: [dupppaaaa]}]

 Im storing this data in global array []

When i get message from new client (freechat user) my contact list is increasing like that

> [{channelId: 1, users: [example2]}, {channelId: 2, users: [example3]}, {channelId: 3, users: [example5]}, {channelId: 5, users: [dupppaaaa]}, {channelId: 6, users: [TVD]}]

Problem is that I have no idea how to rebuild widget, data is displaying after hot reload. Should i write some controller for that ?

To this point I was watching your Android Java Client, sadly it's hard to understand the android java code.

**Comment by DariusPrimarius** [comment]
Screenshots : 
![Screenshot_1704253226](https://github.com/youngmonkeys/freechat/assets/69729379/dac6270b-700b-4647-939a-31cc6b84692c)
![Screenshot_1704253010](https://github.com/youngmonkeys/freechat/assets/69729379/e04de2a4-995d-41a9-a0fb-6ca28ccbca0e)
![Screenshot_1704253179](https://github.com/youngmonkeys/freechat/assets/69729379/f0eeb110-11f3-4eb7-b0fb-4895a75484c0)

**Comment by DariusPrimarius** [comment]
My Idea is to use event handler separately to data handler to get callback and run function which rebuilds the widget with set state(){} but at the moment I'm done.

**Comment by tvd12** [comment]
is your repo is public? could you share it for me? I you can not I will create my own repo to reproduce, thank you
