### ISSUE TITLE
Android shows every contact message on same screen.

### ISSUE THREAD

**Issue by DariusPrimarius** [youngmonkeys/freechat#29]
I used 3 emulators to check that, on each emulator I ran android client with different user. But while sending message I saw all senders messages on the same screen. But sending messages are going still only to the choosen user.

**Comment by tvd12** [comment]
@DariusPrimarius could you try to pull the latest source code and run again? And could you take a look debug logs, did you see any log like bellow?

```
D/ezyfox-client: main | received command: APP_REQUEST and data: [1, [6, {from=xxx, message=xxx, channelId=x}]]
```

**Comment by DariusPrimarius** [comment]
Sorry for that it took so long. I recently forked repo 'freechat' with
flutter-client directory im working on.

czw., 4 sty 2024 o 05:22 Ta Van Dung ***@***.***> napisał(a):

**Comment by tvd12** [comment]
so you can close this issue if you don't need it anymore, thank you
