### ISSUE TITLE
encrypted, p2p, private?

### ISSUE THREAD

**Issue by sjb8100** [youngmonkeys/freechat#4]
Hi tvd12,

After wising up to how little control we have from other mainstream chat solutions, I realized ezyfox chat might be the solution.

Assuming we host our own ezyfox server and setup freechat, are we better than average protected. Are messages encrypted? Are there message logs or is this p2p. Can we purge the message logs.

this is a basic overview request for info. on the security and privacy the ezyfox freechat example. And possible expansion.

thank for your time, I will try to get back on skype soon. been busy as i am sure you remain.

**Comment by tvd12** [comment]
sorry for my late answer
freechat is a client-server chat application. At the moment freechat is  very simple, you can take a fork to make it better, I can support you if you need
please take a look to know futher about freechat: https://drive.google.com/open?id=1MKfHyJY8_8Pe66n1TmBGG9I06ro0LjTn
Thanks
